schema_version = "1.0.0"
id = "rhino_3d_rotate"
version = "1.0.3"
name = "3D Rotate"
tagline = "CAD-style 3D Reference Rotation with Visual Compass & Native Snapping."
maintainer = "Anupska"
type = "add-on"
blender_version_min = "4.0.0"
license = [
    "SPDX:GPL-3.0-or-later",
]
